Run integ tests for 0.52.0

diff --git a/tools/bump-version b/tools/bump-version
--- a/tools/bump-version
+++ b/tools/bump-version
@@ -105,11 +105,11 @@ cd "${_repo_root}"
 git pull --tags
 
 
-# Ensure clean git status
-# if ! git diff --quiet; then
-#     echo "Error: Git status is not clean. Please commit or stash your changes."
-#     exit 1
-# fi
+Ensure clean git status
+if ! git diff --quiet; then
+    echo "Error: Git status is not clean. Please commit or stash your changes."
+    exit 1
+fi
 
 PRE_BUMP_VERSION=$(grep "current_version =" tools/versions/engine.cfg | awk '{print $3}')
 
@@ -136,7 +136,7 @@ fi
 
 cd "${_repo_root}/tools"
 if [ "$_all_mode" -eq 1 ]; then
-  bump2version --config-file ./versions/engine.cfg $version_bump --allow-dirty
+  bump2version --config-file ./versions/engine.cfg $version_bump
   bump2version --config-file ./versions/python.cfg $version_bump --allow-dirty
   bump2version --config-file ./versions/typescript.cfg $version_bump --allow-dirty
   bump2version --config-file ./versions/ruby.cfg $version_bump --allow-dirty
@@ -205,8 +205,6 @@ poetry run baml-cli generate --from ../baml_src
 # Now run integ tests for each
 cd "${_repo_root}/integ-tests/typescript"
 # Echo version and date to integ-tests.log
-echo "Version: $NEW_VERSION" > integ-tests.log
-echo "Date: $(date)" >> integ-tests.log
 if pnpm integ-tests:ci; then
     ts_tests_status="✅ Typescript integ tests"
 else
@@ -216,19 +214,18 @@ fi
 
 cd "${_repo_root}/integ-tests/python"
 # Echo version and date to integ-tests.log
-echo "Version: $NEW_VERSION" > integ-tests.log
-echo "Date: $(date)" >> integ-tests.log
-if $(infisical run --env=test -- poetry run pytest --template=html1/index.html --report=report.html); then
+if infisical run --env=test -- poetry run pytest --template=html1/index.html --report=report.html; then
     python_tests_status="✅ Python integ tests"
 else
     python_tests_status="❌ Python integ tests"
     echo "Python integ tests failed, but continuing..."
 fi
 
+cd "${_repo_root}"
 git add .
 
 git commit -m "Run integ tests for $NEW_VERSION"
 
 echo "All done! Please push the branch $_branch_name and create a PR."
 
-gh pr create --base main --head $_branch_name --title "chore: Bump version to $NEW_VERSION" --body "Bump version to $NEW_VERSION\n\n$ts_tests_status\n$python_tests_status\n\nGenerated by bump-version script."
+gh pr create --title "chore: Bump version to $NEW_VERSION" --body "Bump version to $NEW_VERSION\n\n$ts_tests_status\n$python_tests_status\n\nGenerated by bump-version script."
