one last fix

diff --git a/.github/workflows/build-python-release.reusable.yaml b/.github/workflows/build-python-release.reusable.yaml
--- a/.github/workflows/build-python-release.reusable.yaml
+++ b/.github/workflows/build-python-release.reusable.yaml
@@ -68,23 +68,6 @@ jobs:
     runs-on: ${{ matrix._.runs_on }}
     # See also https://github.com/mcrumiller/polars/.github/workflows/release-python.yml#L282
     steps:
-      - name: Test LICENSE packaging
-        if: matrix._.license_test != 'skip'
-        run: |
-          set -euo pipefail
-
-          mkdir -p ../python-license-test
-          cd ../python-license-test
-          uv init --bare --python 3.10
-          uv add pip-licenses-cli
-          pwd
-          ls ../baml/engine/language_client_python/dist/
-          uv pip install $(ls ../baml/engine/language_client_python/dist/*.whl)
-          uv run pip-licenses | tee license-audit.log
-
-          # Due to `set -e`, this will fail if no matches are found
-          grep 'baml.*Apache-2.0' license-audit.log
-
       - name: Setup build environment (ARM64 Windows)
         if: matrix._.target == 'aarch64-pc-windows-msvc'
         shell:
@@ -170,6 +153,23 @@ jobs:
 
       - name: Install uv
         uses: astral-sh/setup-uv@v6
+
+      - name: Test LICENSE packaging
+        if: matrix._.license_test != 'skip'
+        run: |
+          set -euo pipefail
+
+          mkdir -p ../python-license-test
+          cd ../python-license-test
+          uv init --bare --python 3.10
+          uv add pip-licenses-cli
+          pwd
+          ls ../baml/engine/language_client_python/dist/
+          uv pip install $(ls ../baml/engine/language_client_python/dist/*.whl)
+          uv run pip-licenses | tee license-audit.log
+
+          # Due to `set -e`, this will fail if no matches are found
+          grep 'baml.*Apache-2.0' license-audit.log >/dev/null
 
       - name: Upload wheels
         uses: actions/upload-artifact@v4
