methinks is fixed

diff --git a/.github/workflows/build-python-release.reusable.yaml b/.github/workflows/build-python-release.reusable.yaml
--- a/.github/workflows/build-python-release.reusable.yaml
+++ b/.github/workflows/build-python-release.reusable.yaml
@@ -36,19 +36,23 @@ jobs:
             #   # Workaround ring 0.17 build issue
             #   # see https://github.com/briansmith/ring/issues/1728
             #   CFLAGS_aarch64_unknown_linux_gnu: "-D__ARM_ARCH=8"
+            run_license_test: false
 
           - target: x86_64-unknown-linux-musl
             runs_on: ubuntu-latest
             # see https://github.com/astral-sh/uv/blob/9bb55c4ac0582e05d1a7a5bbd99cc7b2c82f1847/.github/workflows/build-binaries.yml#L594
             manylinux: musllinux_1_1
+            run_license_test: false
 
           - target: aarch64-unknown-linux-musl
             runs_on: ubuntu-latest
             # see https://github.com/astral-sh/uv/blob/9bb55c4ac0582e05d1a7a5bbd99cc7b2c82f1847/.github/workflows/build-binaries.yml#L594
             manylinux: musllinux_1_1
+            run_license_test: false
 
           - target: x86_64-apple-darwin
             runs_on: macos-latest
+            run_license_test: false
 
           - target: aarch64-apple-darwin
             runs_on: macos-latest
@@ -64,6 +68,23 @@ jobs:
     runs-on: ${{ matrix._.runs_on }}
     # See also https://github.com/mcrumiller/polars/.github/workflows/release-python.yml#L282
     steps:
+      - name: Test LICENSE packaging
+        if: matrix._.run_license_test != false
+        run: |
+          set -euo pipefail
+
+          mkdir -p ../python-license-test
+          cd ../python-license-test
+          uv init --bare --python 3.10
+          uv add pip-licenses-cli
+          pwd
+          ls ../baml/engine/language_client_python/dist/
+          uv pip install $(ls ../baml/engine/language_client_python/dist/*.whl)
+          uv run pip-licenses | tee license-audit.log
+
+          # Due to `set -e`, this will fail if no matches are found
+          grep 'baml.*Apache-2.0' license-audit.log
+
       - name: Setup build environment (ARM64 Windows)
         if: matrix._.target == 'aarch64-pc-windows-msvc'
         shell:
@@ -149,22 +170,6 @@ jobs:
 
       - name: Install uv
         uses: astral-sh/setup-uv@v6
-
-      - name: Test LICENSE packaging
-        run: |
-          set -euo pipefail
-
-          mkdir -p ../python-license-test
-          cd ../python-license-test
-          uv init --bare --python 3.10
-          uv add pip-licenses-cli
-          pwd
-          ls ../baml/engine/language_client_python/dist/
-          uv pip install $(ls ../baml/engine/language_client_python/dist/*.whl)
-          uv run pip-licenses | tee license-audit.log
-
-          # Due to `set -e`, this will fail if no matches are found
-          grep 'baml.*Apache-2.0' license-audit.log
 
       - name: Upload wheels
         uses: actions/upload-artifact@v4
