add datadog dep to integ test in go

diff --git a/.github/workflows/primary.yml b/.github/workflows/primary.yml
--- a/.github/workflows/primary.yml
+++ b/.github/workflows/primary.yml
@@ -172,7 +172,8 @@ jobs:
 
       - name: Test Generators (1 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm build:debug && pnpm generate || (echo "::error:: merge canary and run codegen again" && exit 1)
+        working-directory: integ-tests/typescript
 
       - name: Ensure No Changes (1 of 3)
         run: |
@@ -180,7 +181,8 @@ jobs:
 
       - name: Test Generators (2 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm build:debug && pnpm generate || (echo "::error:: merge canary and run codegen again" && exit 1)
+        working-directory: integ-tests/typescript
 
       - name: Ensure No Changes (2 of 3)
         run: |
@@ -188,7 +190,8 @@ jobs:
 
       - name: Test Generators (3 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm build:debug && pnpm generate || (echo "::error:: merge canary and run codegen again" && exit 1)
+        working-directory: integ-tests/typescript
 
       - name: Ensure No Changes (3 of 3)
         run: |
