[FIXME] Try using `integ-tests` instead of typescript sdk
If this works:

FIXME: needs merging w/ commits that did *not* work out.

diff --git a/.github/workflows/primary.yml b/.github/workflows/primary.yml
--- a/.github/workflows/primary.yml
+++ b/.github/workflows/primary.yml
@@ -158,6 +158,10 @@ jobs:
 
       - name: Setup Node.js
         uses: ./.github/actions/setup-node
+        with:
+          # TODO: re-enable it once I can solve the problem with baml-cli.
+          frozen-lockfile: false
+
 
       - name: Setup Rust
         uses: ./.github/actions/setup-rust
@@ -168,7 +172,7 @@ jobs:
 
       - name: Test Generators (1 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm generate --force --filter=@baml/integ-tests || (echo "::error:: merge canary and run codegen again" && exit 1)
 
       - name: Ensure No Changes (1 of 3)
         run: |
@@ -177,7 +181,7 @@ jobs:
 
       - name: Test Generators (2 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm generate --force --filter=@baml/integ-tests || (echo "::error:: merge canary and run codegen again" && exit 1)
 
       - name: Ensure No Changes (2 of 3)
         run: |
@@ -185,7 +189,7 @@ jobs:
 
       - name: Test Generators (3 of 3)
         run: |
-          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm generate --force --filter=@baml/integ-tests || (echo "::error:: merge canary and run codegen again" && exit 1)
 
       - name: Ensure No Changes (3 of 3)
         run: |
