ci/test-generators: Run generation three times and assert no changes

diff --git a/.github/workflows/primary.yml b/.github/workflows/primary.yml
--- a/.github/workflows/primary.yml
+++ b/.github/workflows/primary.yml
@@ -164,11 +164,28 @@ jobs:
           enable-cross: false
           cache-on-failure: true
 
-      - name: Test Generators
+      - name: Test Generators (1 of 3)
         run: |
-          pnpm generate --force || (echo "::error:: merge canary and run codegen again" && exit 1)
+          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
 
-      - name: Ensure No Changes
+      - name: Ensure No Changes (1 of 3)
+        run: |
+          git diff --exit-code || (echo "::error:: merge canary and run codegen again" && exit 1)
+
+
+      - name: Test Generators (2 of 3)
+        run: |
+          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+
+      - name: Ensure No Changes (2 of 3)
+        run: |
+          git diff --exit-code || (echo "::error:: merge canary and run codegen again" && exit 1)
+
+      - name: Test Generators (3 of 3)
+        run: |
+          pnpm generate --force --filter=@boundaryml/baml || (echo "::error:: merge canary and run codegen again" && exit 1)
+
+      - name: Ensure No Changes (3 of 3)
         run: |
           git diff --exit-code || (echo "::error:: merge canary and run codegen again" && exit 1)
 
